name: Ladurner
favicon: null
layout_spectrum: 0.9179358712863177
typography_spectrum: 0.3196193177718669
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.83157819067128
  lightness: 0.357879743212834
  saturation: 0.7986672332044691
  rhythmicContrast: 0.9432723978534341
purpose: []
