name: Ladurner
favicon: null
layout_spectrum: 0
typography_spectrum: 0.35393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#063c7f'
    - '#b60d20'
    - '#7191b7'
    - '#cd5965'
  brandStrength: 0.875
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
